/*CRIACAO DA TABELA USUARIO*/
CREATE TABLE usuario(
	id SERIAL,
	ativo BOOLEAN DEFAULT TRUE NOT NULL,
	email VARCHAR (100) UNIQUE NOT NULL,
	senha VARCHAR (50) NOT NULL,
	nome VARCHAR (50) NOT NULL,
	sobrenome VARCHAR (100) NOT NULL,
	sexo VARCHAR (1) NOT NULL,
	datanasc DATE NOT NULL,
	acesso INT NOT NULL DEFAULT 1,
	telefone VARCHAR(30),
	rua VARCHAR(100),
	cidade VARCHAR(100),
	estado VARCHAR(50),
	numero VARCHAR(10),
	cep VARCHAR(50),
	CONSTRAINT id_pk PRIMARY KEY (id)
);

/*CRIACAO DA TABELA GRUPO*/
CREATE TABLE grupo(
	id SERIAL,
	ativo BOOLEAN DEFAULT TRUE NOT NULL,
	datahora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	nome VARCHAR(50) NOT NULL,
	descricao TEXT,
	foto VARCHAR(16),
	CONSTRAINT id_pk PRIMARY KEY(id),
	CONSTRAINT tam_nome CHECK (DATALENGTH(nome)>=6) 
);

/*CRIACAO DA TABELA TEXTO*/
CREATE TABLE texto(
	id SERIAL,
	ativo BOOLEAN DEFAULT TRU NOT NULL,
	conteudo TEXT,
	datahora DATETIME NOT NULL, DEFAULT CURRENT_TIMESTAMP,
	usuarioid INT,
	CONSTRAINT id_pk PRIMARY KEY(id),
	CONSTRAINT usid_fk FOREIGN KEY (usuarioid) 
		REFERENCES usuario(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

/*CRIACAO DA TABELA COMENTARIO*/
CREATE TABLE comentario(
	textoid INT,
	respondeid INT,
	CONSTRAINT txtid_fk FOREIGN KEY (textoid)
		REFERENCES texto(id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT rspid_fk FOREIGN KEY (respondeid)
		REFERENCES texto(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);


